### PR TITLE
Mise à jour v0.12.20

### PR DESCRIPTION
**Pull request by 4LD**
**Happy new year** @fonsp !!! 🥳
Here my modest PR ^^

I have seen your pull https://github.com/fonsp/pluto-on-binder/pull/8, it's sound great !

Since I have you, I have a question about the good @bind :
```
macro bind(def, element)
    quote
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : missing
        el
    end
end
```

Could it be : _(to define default if needed)_
```
macro bind(def, element, defaultmissing=missing)
    quote
        local el = $(esc(element))
        global $(esc(def)) = Core.applicable(Base.get, el) ? Base.get(el) : defaultmissing
        el
    end
end
```

### CODE REVIEW

**Comment by fonsp** [comment]
Thank you!! And happy new year!

About the macro: that sounds good, I think I understand why you might want this.

I am a little reluctant to change the `@bind` syntax, because after a change, it has to stay that way forever. But I will think about it, in the meatime, take a look at `@initially` from this notebook: https://github.com/fonsp/disorganised-mess/blob/master/plotclicktracker.jl

```julia
@intially [1,2] @bind x something()
```

I needed to make this a macro for the more complex use case of that notebook (which is cool btw, try it out!). But my earlier, simpler attempt was just a function `BondDefault(value, element)`:

https://github.com/fonsp/disorganised-mess/blob/c0332f4a1cc94c4ea02850ef6d19adc143ba186f/plotclicktracker%20experiments.jl#L158-L165

```julia
@bind x BondDefault(something(), [1,2])
```

**Comment by fonsp** [comment]
I was actually considering this syntax to be added to Pluto:
```julia
@bind x=[1,2] something()
```
What do you think?

**Comment by 4LD** [comment]
**Merci Fons 😎**

It's exactly what I wish ! _(my macro was wrong but you got it... and sorry for @Bind)_
I prefer macro style (good notebook ;) than your struct (and [bidouilles](https://www.deepl.com/translator#fr/de/bidouille)) ^^
In fact, it is even better than I wanted ; nevertheless, I would prefer an "all inclusive" `@bind` (your syntax proposed 👍 :)
Do not forget to add this in Pluto.jl samples to document it (when it will come)

**Comment by 4LD** [comment]
... and I am curious, can you add in the [FAQ](https://github.com/fonsp/Pluto.jl/wiki#frequently-asked-questions) why the origin of the _Pluto_'s name? 😜

**Pull request merged**
