### PR TITLE
Add logo and update for latest Pluto

### PR DESCRIPTION
**Pull request by barche**
This adds the logo and updates the `run` command for compatibility with the latest Pluto.jl. The logo makes things look a lot nicer in jupyterlab. I am not a Python expert, so there may be a less contorted way of doing this.

### CODE REVIEW

**Comment by fonsp** [comment]
Thanks! Can you rewrite it to maintain the single-file-package structure? I want this repo to be as slim as possible. Having no folders also means that you can write it in a github gist

**Comment by fonsp** [comment]
Oh and can you describe how you installed this as a jupyter lab extension? Should we register this package with pip? Any other suggestions? https://github.com/fonsp/PlutoUtils.jl/issues/4

**Comment by barche** [comment]
> Thanks! Can you rewrite it to maintain the single-file-package structure? I want this repo to be as slim as possible

Unfortunately I don't know how, I went for the package structure to have a reliable place to put the icon (the logo from Pluto.jl). An alternative might be to refer to the Pluto.jl dir, but that would require starting Julia in `setup_plutoserver` to get the path, which may change when the user updates Pluto.jl.

> Oh and can you describe how you installed this as a jupyter lab extension?

All I needed to do is install the jupyterlab extension for the server proxy, then the package works as-is, adding a button in the jupyterlab launcher:

```
jupyter labextension install @jupyterlab/server-proxy
```

> Should we register this package with pip?

That would be nice, yes. I want to use this in our custom jupyterlab single-user Docker image, having it in pip would make that simpler.

**Comment by fonsp** [comment]
Hey @barche !

I closed this PR because this repository (fonsp/pluto-on-binder) is really for only one purpose: a repository that binder can launch from to run the Pluto demo:

Schermafbeelding 2021-01-06 om 11 25 18

But the other purpose, Pluto as a jupyterlab extension, is something that still needs some work! See the discussion over at https://github.com/fonsp/PlutoUtils.jl/issues/4 and the post by Max Koehler: https://www.maximiliankoehler.de/posts/pluto-server/

**Pull request closed without merging**
