### PR TITLE
MàJ Pluto.jl v0.12.21

### PR DESCRIPTION
**Pull request by 4LD**
Hi @fonsp 

This is a simple bump as usual 🤓
Thanks for the interesting link to the other German guy (http://px16.matt.is) 
-> good thinking (but do not take whole for Pluto 😜)

_I have another question ^^_
Do you think it's a good idea to have in the file picker (or export view) a way to create **_and restore_** a backup ?
Since Pluto.jl have continuous save system, it could be an option to do and redo easily... what do you think ?

### CODE REVIEW

**Comment by 4LD** [comment]
Hi @fonsp 

This is the bump for Pluto v0.14.0 ;)

**Comment by fonsp** [comment]
danke!

**Comment by fonsp** [comment]
Although I love our little interactions, I am very sorry to say that I have now automated this process:

https://github.com/fonsp/pluto-on-binder/actions

https://github.com/fonsp/Pluto.jl/blob/main/.github/workflows/ReleaseBinder.yml

image



But feel welcome to contribute to Pluto in another way! Did you watch last week's PlutoCon? 

https://plutojl.org/plutocon2021

**Comment by fonsp** [comment]
FYI:

I am automating the process because I want to _tag_ Pluto versions in this repository, so that  https://github.com/JuliaPluto/PlutoSliderServer.jl can use binder URLs that link to a fixed Pluto version, the same used during the export process. 

https://github.com/JuliaPluto/PlutoSliderServer.jl/pull/5

**Comment by 4LD** [comment]
Hi @fonsp, you are welcome ! :P

Good point to automate it, and to have a clone version tag from Pluto.jl 👍 
I think I would contribute to Pluto, but it will be more difficult for me to ask you some questions (even if you forget to answer :)
> [_I have another question ^^_](https://github.com/fonsp/pluto-on-binder/pull/12#issue-577185751)
> Do you think it's a good idea to have in the file picker (or export view) a way to create **_and restore_** a backup ?
> Since Pluto.jl have continuous save system, it could be an option to do and redo easily... what do you think ?

_Another new one_ : 
Do you think it's a good idea to see all (or the ability to pin/choose some) _time execution_ ▶ even for **hidden** cells code ?

**Note :** I think, you have this... but be careful with the idea to have it (by default, I mean) in PlutoSliderServer export :
If a specific tag is not used frequently, Binder has to rebuild the whole and take much more time :'(
So, it can be more useful to have the last pluto-on-binder by default (which is usually kept by Binder). 
Pluto.jl seems to be down compatible most of times (thanks to you).
...or point to major tag version...
It's still a good idea to have an option, if needed. 

To finish to your question _(yes... French people speaks perhaps too much... ^^)_
Yes ! 👍 I have seen some of your PlutoCon2021, congratulation and thanks again for your time !!! 😎

**Comment by fonsp** [comment]
> Do you think it's a good idea to see all (or the ability to pin/choose some) time execution ▶ even for hidden cells code ?

Yes! But this can also be done by a package used _inside_ Pluto. For example, the `@elapsed` macro shows how long it took to run, `@benchmark` from BenchmarkTools.jl shows this result but with prettier printing.

What's missing is a macro that show both the computer result and the runtime.

> Binder has to rebuild the whole and take much more time

That's very true! In the case of PlutoSliderServer, connecting to binder in the background means that the Pluto server version needs to exactly match the version used to create the export, they are tied together. But if the goal is just to have a binder link, like with https://pluto-on-binder.glitch.me/ , then an unversioned binder link makes more sense.

I currently implemented the binder.plutojl.org domain just using cloudflare redirect rules:

Schermafbeelding 2021-04-13 om 22 40 51

This is a cool trick, but the limitation is that I can't write more advanced things.

The main problem is: even if `master` is currently tagged at `0.14.1`, they are still two different build caches at binder. So ideally, everyone would use the versioned binder link, to make the cache for `0.14.1` 'hot'.

**Comment by 4LD** [comment]
In this case, *binder.plutojl/* will be updated for each new version, like the new v0.14.2 ?
(if you wanted it hot)
There is no easy way :)

**Pull request merged**
